<?php

########################################################################
# Extension Manager/Repository config file for ext: "slub_web_addressbooks"
#
# Auto generated by Extension Builder 2013-05-02
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SLUB Adressbuecher',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Alexander Bigga',
	'author_email' => 'typo3@slub-dresden.de',
	'author_company' => 'SLUB Dresden',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '3.0.4',
	'constraints' => array(
		'depends' => array(
			'typo3' => '9.5.0-10.4.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
